export type ResourceBlock =
  | { kind: "paragraph"; text: string }
  | { kind: "heading"; text: string }
  | { kind: "quote"; text: string }
  | { kind: "list"; items: string[] }
  | { kind: "leadList"; items: { lead: string; text: string }[] }
  | { kind: "callout"; label: string; text: string; tone?: "warning" | "takeaway" | "rule" }
  | { kind: "divider" }
  | { kind: "table"; columns: [string, string]; rows: [string, string][] }
  | { kind: "image"; src: string; alt: string; caption: string };

export const resourceArticles: Record<string, {
  deck: string;
  readingTime: string;
  blocks: ResourceBlock[];
}> = {
  "could-your-business-run-for-two-weeks-without-you": {
    deck: "A practical founder independence test for identifying where normal business activity still depends on your personal involvement.",
    readingTime: "5 minutes",
    blocks: [
      { kind: "paragraph", text: "There is a strange milestone many successful founders eventually reach." },
      { kind: "leadList", items: [
        { lead: "The business is growing", text: "The team is bigger and revenue is up." },
        { lead: "The pressure is rising", text: "More decisions, questions, and exceptions seem to depend on you than ever before." },
      ] },
      { kind: "paragraph", text: "That is not automatically a leadership failure. In the early stages, founder involvement is often an advantage. You know the customers, make decisions quickly, solve unusual problems, and carry knowledge that helped build the company." },
      { kind: "paragraph", text: "But what works at $1 million can become a constraint at $5 million or $10 million. Eventually, being indispensable stops being an advantage. It becomes an operating risk." },
      { kind: "callout", label: "Core idea", tone: "takeaway", text: "The goal is not to remove the founder from the business. The goal is to remove the founder from work that should not require them." },
      { kind: "divider" },
      { kind: "heading", text: "Involvement and dependency are not the same thing" },
      { kind: "paragraph", text: "A founder should remain involved in decisions where their judgment creates disproportionate value: strategy, capital allocation, senior leadership, major relationships, and direction." },
      { kind: "paragraph", text: "That is strategic involvement." },
      { kind: "paragraph", text: "Dependency is different. Dependency exists when normal business activity cannot continue without your personal intervention." },
      { kind: "table", columns: ["Strategic involvement", "Operational dependency"], rows: [
        ["The business benefits from your presence.", "The business requires your presence."],
        ["Your judgment improves important decisions.", "Normal work waits for your intervention."],
        ["Your role creates leverage.", "Your role becomes a bottleneck."],
      ] },
      { kind: "callout", label: "Founder test", tone: "rule", text: "Involvement means the business benefits from your presence. Dependency means the business requires it." },
      { kind: "paragraph", text: "That difference has consequences for growth, leadership capacity, and eventually enterprise value." },
      { kind: "heading", text: "The six places founder dependency tends to hide" },
      { kind: "paragraph", text: "Founder dependency rarely exists in just one place. Look across these six zones." },
      { kind: "leadList", items: [
        { lead: "Sales and closing", text: "Deals progress until the customer wants pricing flexibility, reassurance, or final approval. Then the founder gets pulled in." },
        { lead: "Key client relationships", text: "Important customers trust you personally. The relationship may belong more to the founder than to the company." },
        { lead: "Technical and delivery knowledge", text: "When something unusual happens, everyone knows who has the answer. Unfortunately, that answer may exist only in your head." },
        { lead: "Financial approvals", text: "Purchases, discounts, hiring decisions, refunds, and exceptions accumulate because nobody knows what they can authorize without you." },
        { lead: "Team problem solving", text: "Managers escalate problems instead of resolving them because decision rights, operating rules, or confidence have not been developed." },
        { lead: "Tactical execution", text: "You are still reviewing proposals, fixing presentations, chasing projects, reconciling reports, or stepping into workflows simply to keep things moving." },
      ] },
      { kind: "callout", label: "Operational warning", tone: "warning", text: "None of these behaviors looks catastrophic individually. Together, they create a business whose operating capacity is constrained by one person's availability." },
      { kind: "divider" },
      { kind: "heading", text: "Try the Two-Week Absence Test" },
      { kind: "paragraph", text: "Imagine that tomorrow morning you become completely unavailable for 14 calendar days." },
      { kind: "leadList", items: [
        { lead: "No working vacation", text: "No email, Slack, text messages, or quick questions." },
        { lead: "No quiet monitoring", text: "No checking dashboards from the beach." },
        { lead: "No invisible intervention", text: "No stepping in to move work forward behind the scenes." },
      ] },
      { kind: "paragraph", text: "What happens?" },
      { kind: "list", items: [
        "Which customer issue remains unresolved?",
        "Which deal cannot close?",
        "Which payment waits for approval?",
        "Which employee does not know what decision to make?",
        "Which report does not get produced?",
        "Which process stops because the next step exists in your head rather than in the operating system?",
      ] },
      { kind: "callout", label: "Stress test", tone: "rule", text: "This is not really a vacation test. It is a stress test for your business." },
      { kind: "paragraph", text: "Every meaningful activity that stops gives you information about where operational dependency exists. Those dependencies tell you where to start." },
      { kind: "heading", text: "Do not try to remove yourself from everything" },
      { kind: "paragraph", text: "Founder independence does not mean founder irrelevance. The objective is not to disappear from the company. It is to remove yourself from work that should not require you." },
      { kind: "paragraph", text: "Start with three moves." },
      { kind: "heading", text: "1. Audit the decisions that repeatedly reach you" },
      { kind: "paragraph", text: "For two weeks, keep a simple decision log." },
      { kind: "list", items: [
        "What reached you?",
        "Who brought it to you?",
        "Why could they not decide?",
        "What information or authority was missing?",
      ] },
      { kind: "paragraph", text: "Patterns will emerge quickly." },
      { kind: "heading", text: "2. Systemize the single points of failure" },
      { kind: "paragraph", text: "Identify processes where only one person knows how something works, especially when that person is you." },
      { kind: "paragraph", text: "Document the workflow, exceptions, inputs, decision rules, and expected outcomes. Do not document everything. Start with the processes whose failure would cause the greatest disruption." },
      { kind: "heading", text: "3. Delegate authority, not just tasks" },
      { kind: "paragraph", text: "This is where many delegation efforts fail. Giving someone responsibility without decision authority simply creates a messenger." },
      { kind: "leadList", items: [
        { lead: "Decision rights", text: "What can they decide?" },
        { lead: "Financial thresholds", text: "Up to what dollar amount?" },
        { lead: "Escalation rules", text: "Which exceptions require escalation?" },
        { lead: "Communication rules", text: "When should you be informed rather than consulted?" },
      ] },
      { kind: "callout", label: "Operating goal", tone: "takeaway", text: "The goal is not fewer decisions. The goal is fewer unnecessary decisions reaching the founder." },
      { kind: "divider" },
      { kind: "heading", text: "Your business should become more capable as it grows" },
      { kind: "paragraph", text: "Here is the question I would leave you with." },
      { kind: "quote", text: "If you disappeared tomorrow for two weeks, what are the first three things that would break?" },
      { kind: "paragraph", text: "Do not dismiss the answers as inconveniences. They are showing you where your operating system still depends on a person instead of a capability." },
      { kind: "paragraph", text: "And if the answer is, more than I would like to admit, that is exactly where the work begins." },
      { kind: "paragraph", text: "At RunRate Advisory, we help founders identify these dependencies and turn them into clearer decision rights, repeatable workflows, better management visibility, and scalable operating systems." },
      { kind: "callout", label: "Next step", tone: "rule", text: "Put your business through the Two-Week Absence Test. Write down the first three things you believe would break, then use those answers to identify where dependency should be addressed first." },
    ],
  },
  "executive-reports-that-drive-action": {
    deck: "Separate useful operating signals from management noise. Redesign reporting around the decisions it should drive, not the history it explains.",
    readingTime: "6 minutes",
    blocks: [
      { kind: "paragraph", text: "Most leadership teams do not have a reporting problem. They have a decision problem." },
      { kind: "paragraph", text: "Every month, executives invest hours gathering reports from CRM systems, accounting software, spreadsheets, project management tools, and email threads. The information eventually lands in a board deck or management report that explains what happened last month." },
      { kind: "paragraph", text: "The problem is that by the time the report is complete, the decisions that could have changed the outcome have already passed. Reporting should reduce uncertainty, not create another administrative task." },
      { kind: "callout", label: "Executive question", tone: "rule", text: "Does your reporting help you run the business, or merely describe it?" },
      { kind: "divider" },
      { kind: "heading", text: "The executive reporting trap" },
      { kind: "paragraph", text: "Most organizations unknowingly pay what RunRate calls the Last-Minute Assembly Tax. Someone exports CRM data. Finance updates spreadsheets. Operations sends production numbers. Sales managers revise forecasts. Leadership waits while someone reconciles conflicting figures." },
      { kind: "paragraph", text: "By the time everything is assembled, several hours or even days have been consumed simply trying to answer a basic question: what is actually happening in the business?" },
      { kind: "callout", label: "Key takeaway", tone: "takeaway", text: "If executives must manually assemble the truth every reporting cycle, the reporting system itself has become operational work." },
      { kind: "image", src: "/insights/stuck-in-reporting-trap.png", alt: "Illustration of manual data assembly across disconnected CRM, finance, operations, and project systems", caption: "The Last-Minute Assembly Tax: manual, siloed reporting consumes leadership time before decisions can be made." },
      { kind: "heading", text: "Rearview mirror management" },
      { kind: "paragraph", text: "Traditional executive reports are designed to explain the past: revenue versus budget, gross margin versus prior year, operating expenses, pipeline summaries, utilization, and customer satisfaction. These metrics are useful, but by themselves they rarely improve performance." },
      { kind: "table", columns: ["Historical reporting", "Decision-driven reporting"], rows: [
        ["Explains what happened", "Surfaces what is changing"],
        ["Reviews lagging metrics", "Highlights leading signals"],
        ["Produces discussion", "Triggers decisions"],
        ["Requires manual assembly", "Creates operating visibility"],
      ] },
      { kind: "paragraph", text: "Historical reports answer questions like these." },
      { kind: "leadList", items: [
        { lead: "Past performance", text: "What happened?" },
        { lead: "Target review", text: "How did we perform?" },
        { lead: "Variance explanation", text: "Where did we miss target?" },
      ] },
      { kind: "paragraph", text: "Leadership teams also need reports that answer different questions." },
      { kind: "leadList", items: [
        { lead: "Change signals", text: "What is changing?" },
        { lead: "Risk visibility", text: "Where is risk increasing?" },
        { lead: "Decision focus", text: "Which decision requires attention this week?" },
        { lead: "Next action", text: "What should we do next?" },
      ] },
      { kind: "image", src: "/insights/rearview-mirror-management.png", alt: "Split illustration comparing rearview mirror management with live operating signals", caption: "Historical reporting explains what already happened. Decision-ready reporting surfaces signals while there is still time to act." },
      { kind: "divider" },
      { kind: "heading", text: "Signal versus noise" },
      { kind: "paragraph", text: "A common misconception is that better reporting means more metrics. In reality, more metrics usually create more interpretation. When every dashboard contains dozens of charts, executives spend meetings debating numbers rather than making decisions." },
      { kind: "callout", label: "Executive rule", tone: "rule", text: "Every executive metric should either trigger a decision, confirm a strategic assumption, or highlight emerging risk." },
      { kind: "image", src: "/insights/signal-or-management-noise.png", alt: "Funnel diagram filtering management noise into actionable operating signals", caption: "A decision-driven filter turns scattered reporting noise into a short list of signals that deserve executive attention." },
      { kind: "heading", text: "Redesign reporting around decisions" },
      { kind: "paragraph", text: "The most effective leadership teams reverse the traditional reporting model. Instead of starting with available data, they start with recurring executive decisions." },
      { kind: "leadList", items: [
        { lead: "Capacity decisions", text: "Should we hire additional capacity?" },
        { lead: "Revenue risk", text: "Is revenue at risk this quarter?" },
        { lead: "Customer attention", text: "Which customers require executive attention?" },
        { lead: "Delivery confidence", text: "Are delivery commitments achievable?" },
        { lead: "Investment priority", text: "Where should investment be prioritized?" },
      ] },
      { kind: "heading", text: "Identify your operating signals" },
      { kind: "paragraph", text: "Every business has a small number of indicators that influence overall performance. These are not vanity metrics. They are operating signals: qualified pipeline coverage, weekly conversion, capacity utilization, backlog health, cash collection, customer delays, open risks, and forecast confidence." },
      { kind: "paragraph", text: "The exact signals vary by industry, but the principle stays the same. Executives should monitor the few indicators that provide early visibility into future outcomes, not the ones that simply confirm historical results." },
      { kind: "heading", text: "Define intervention thresholds" },
      { kind: "paragraph", text: "Information becomes actionable only when leaders know what requires intervention. Each operating signal should include predefined thresholds: green for healthy, amber for review, and red for executive action." },
      { kind: "callout", label: "Operating point", tone: "takeaway", text: "Without thresholds, dashboards simply report variation. With thresholds, they guide attention." },
      { kind: "divider" },
      { kind: "heading", text: "Build an automated truth engine" },
      { kind: "paragraph", text: "Decision-driven reporting depends on one source of operational truth. Most organizations already have the information they need. The challenge is that it lives across disconnected systems, including CRM, accounting, project management, operations tools, and spreadsheets." },
      { kind: "leadList", items: [
        { lead: "Core systems", text: "Integrate the systems that produce operating data." },
        { lead: "Definitions", text: "Standardize the meaning of every executive metric." },
        { lead: "Duplicate entry", text: "Eliminate repeated manual entry wherever practical." },
        { lead: "Calculations", text: "Automate recurring KPI and exception calculations." },
        { lead: "Visibility", text: "Present information visually so leaders can act quickly." },
      ] },
      { kind: "heading", text: "A practical framework for leadership" },
      { kind: "leadList", items: [
        { lead: "Audit reports", text: "Document every recurring report, preparation time, manual effort, source system, and duplicated metric." },
        { lead: "Map decisions", text: "Connect recurring executive decisions to the smallest set of leading indicators needed to support them." },
        { lead: "Automate flow", text: "Automate recurring data movement, KPI updates, exception monitoring, and executive summaries." },
        { lead: "Manage exceptions", text: "Use meetings for risks, deviations, decisions, and corrective action." },
      ] },
      { kind: "image", src: "/insights/automated-visibility-plan.png", alt: "Three-step plan for improving executive reporting and automated visibility", caption: "A practical sequence: audit the current reporting stack, map decisions to lead indicators, then automate recurring data flow." },
      { kind: "heading", text: "Where to begin" },
      { kind: "paragraph", text: "If your executive team still spends hours collecting, reconciling, and validating information before every management meeting, the reporting process itself deserves attention." },
      { kind: "leadList", items: [
        { lead: "Manual effort", text: "Identify the hidden work inside your reporting cycle." },
        { lead: "Operating signals", text: "Clarify which signals truly drive executive decisions." },
        { lead: "Data movement", text: "Automate repetitive information transfer." },
        { lead: "Exception design", text: "Design dashboards around exceptions rather than historical explanation." },
      ] },
    ],
  },
  "automation-before-ai": {
    deck: "Do not automate a process you do not understand. Automation magnifies unclear ownership and process variation.",
    readingTime: "7 minutes",
    blocks: [
      { kind: "paragraph", text: "Businesses have never had more access to automation and artificial intelligence. Every week, a new platform promises to eliminate repetitive work, increase productivity, or transform operations with AI-powered workflows." },
      { kind: "paragraph", text: "For business owners under pressure to do more with less, the temptation is understandable: buy the software, connect a few systems, and expect efficiency to follow. Unfortunately, that is not how operational excellence gets built." },
      { kind: "callout", label: "Operational warning", tone: "warning", text: "Automation does not fix broken processes. It amplifies them." },
      { kind: "paragraph", text: "If ownership is unclear, automation accelerates confusion. If people perform the same task three different ways, automation scales inconsistency. If employees rely on spreadsheets, email chains, and undocumented workarounds to get work done, automation makes those workarounds faster." },
      { kind: "divider" },
      { kind: "heading", text: "The automation trap" },
      { kind: "paragraph", text: "Technology is very good at executing defined, repeatable work. What it cannot do is compensate for poor operating design." },
      { kind: "table", columns: ["Weak sequence", "Stronger sequence"], rows: [
        ["Current process", "Current process"],
        ["Buy software", "Clarify"],
        ["Automate", "Simplify, standardize, then automate"],
      ] },
      { kind: "paragraph", text: "Many organizations follow the wrong sequence: current process, buy software, automate. The stronger sequence is current process, clarify, simplify, standardize, automate." },
      { kind: "callout", label: "Key takeaway", tone: "takeaway", text: "Technology scales process quality. If the process is poor, the outcome becomes poor at greater speed." },
      { kind: "heading", text: "Where operational friction really comes from" },
      { kind: "paragraph", text: "Organizations often attribute delays to people. More often, the problem is the system surrounding those people. Three patterns show up repeatedly." },
      { kind: "heading", text: "1. Unclear ownership" },
      { kind: "paragraph", text: "Many workflows have participants but very few true owners. When ownership is ambiguous, approvals wait unnecessarily, decisions escalate by default, accountability becomes difficult, and work stalls between departments." },
      { kind: "callout", label: "Diagnostic question", tone: "rule", text: "Who owns this process from beginning to end? If the answer requires three minutes of discussion, ownership is already unclear." },
      { kind: "heading", text: "2. Process variation" },
      { kind: "paragraph", text: "Ask three employees how they complete the same recurring task. Many businesses get three different answers because each employee has developed a version that works." },
      { kind: "paragraph", text: "Over time, those differences create inconsistent customer experiences, reporting discrepancies, training challenges, quality variation, and automation failures." },
      { kind: "heading", text: "3. Shadow systems" },
      { kind: "paragraph", text: "One of the strongest signs of operational friction is the existence of unofficial systems: personal spreadsheets, handwritten notes, private task lists, email reminders, duplicated data entry, and unofficial approval trackers." },
      { kind: "paragraph", text: "Employees rarely build shadow systems because they enjoy extra work. They build them because the official process no longer supports reality." },
      { kind: "image", src: "/insights/hidden-sources-operational-friction.png", alt: "Diagram showing unclear ownership, process variation, and shadow systems as sources of operational friction", caption: "Three common sources of friction: unclear ownership, process variation, and shadow systems. These must be clarified before automation can create value." },
      { kind: "divider" },
      { kind: "heading", text: "The pre-automation blueprint" },
      { kind: "paragraph", text: "Businesses that implement automation successfully tend to follow a disciplined approach before selecting technology." },
      { kind: "leadList", items: [
        { lead: "Map the real workflow", text: "Document the process as it operates today, not how leadership believes it operates." },
        { lead: "Challenge every activity", text: "Remove unnecessary steps before automating them." },
        { lead: "Clarify accountability", text: "Establish one accountable owner, supporting contributors, escalation triggers, approval limits, and success measures." },
      ] },
      { kind: "callout", label: "Core rule", tone: "rule", text: "You cannot improve what you cannot clearly describe." },
      { kind: "image", src: "/insights/pre-automation-blueprint.png", alt: "Blueprint showing workflow mapping, simplification, and accountability before automation", caption: "The pre-automation blueprint: understand the workflow, simplify it, then assign clear accountability before selecting technology." },
      { kind: "heading", text: "Applying practical AI and automation" },
      { kind: "paragraph", text: "Once workflows have been clarified and standardized, AI becomes a force multiplier. The question shifts from where can we use AI to which work should AI perform." },
      { kind: "paragraph", text: "The highest-value automation candidates are repetitive, rules-based, high volume, consistent, measurable, and low judgment." },
      { kind: "leadList", items: [
        { lead: "Recurring reporting", text: "Reports that follow the same cadence and definitions." },
        { lead: "Data reconciliation", text: "Repeated checks across systems or spreadsheets." },
        { lead: "Document routing", text: "Standard routing based on known conditions." },
        { lead: "Notification workflows", text: "Routine alerts, reminders, and exception messages." },
        { lead: "Information retrieval", text: "Finding standard information from approved sources." },
        { lead: "Routine approvals", text: "Low-judgment approvals within defined thresholds." },
      ] },
      { kind: "paragraph", text: "The objective is not replacing people. It is removing repetitive work so people spend more time applying judgment where it matters." },
      { kind: "image", src: "/insights/where-practical-ai-creates-value.png", alt: "Diagram showing where practical AI creates value after workflow clarity exists", caption: "Practical AI creates value after workflow clarity exists, not before." },
      { kind: "divider" },
      { kind: "heading", text: "Choose workflows before choosing tools" },
      { kind: "paragraph", text: "One of the most common implementation mistakes is selecting software first. Organizations get excited by platform demonstrations and then try to reshape operations around the application." },
      { kind: "paragraph", text: "Begin with the workflow. Understand the required outcome, which information must move, where decisions occur, who owns each stage, and which integrations are actually necessary." },
      { kind: "callout", label: "Final operating principle", tone: "warning", text: "Automation is a force multiplier. Make sure you are multiplying order, not chaos." },
      { kind: "heading", text: "Where to begin" },
      { kind: "paragraph", text: "If your organization is evaluating AI, workflow automation, or process improvement, resist the urge to start with technology. Start by understanding how work actually gets done." },
      { kind: "leadList", items: [
        { lead: "Map workflows", text: "Document how recurring work actually moves." },
        { lead: "Clarify ownership", text: "Define who is accountable from start to finish." },
        { lead: "Reduce complexity", text: "Remove unnecessary handoffs, approvals, and workarounds." },
        { lead: "Automate last", text: "Automate only what remains clear, repeatable, and governed." },
      ] },
    ],
  },
};
